apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ap-postgres-claim
  name: ap-postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ap-redis-claim
  name: ap-redis-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
