#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: ibga-pv-volume
#  labels:
#    type: local
#spec:
#  storageClassName: manual
#  capacity:
#    storage: 10Gi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/ibga"
#
#---
#
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  creationTimestamp: null
#  labels:
#    io.kompose.service: ibga-claim0
#  name: ibga-claim0
#spec:
#  storageClassName: manual
#  volumeName: ibga-pv-volume
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 10Gi
#status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: ibga
  name: ibga-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
