apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jackett
  name: jackett-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
