# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: live-ide-pv-volume
# spec:
#   capacity:
#     storage: 10Gi  # Specify the storage capacity for the PV
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain  # How the volume should be handled when released
#   storageClassName: local-storage
#   local:
#     path: "/config/live-workspace"
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - vmi1686791.contaboserver.net  # Specify the node where the storage resides

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: live-ide-claim
spec:
  # storageClassName: local-storage  # Specify the storage class
  # volumeName: live-ide-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Request the amount of storage needed
