apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pihole
  name: pihole-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
