apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-download-pv
spec:
  capacity:
    storage: 10Gi  # Specify the storage capacity for the PV
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # How the volume should be handled when released
  storageClassName: local-storage
  local:
    path: /qbit-downloads  # Path to the local storage directory on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi1845832.contaboserver.net  # Specify the node where the storage resides
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-download-pvc
spec:
  storageClassName: local-storage  # Specify the storage class
  volumeName: qbittorrent-download-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Request the amount of storage needed

