apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
