apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wireguard
  name: wireguard-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wireguard
  name: wireguard-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
