image:
  # -- The repository to pull the image from.
  repository: ghcr.io/pascaliske/unbound
  # -- The docker tag, if left empty chart's appVersion will be used.
  # @default -- `.Chart.AppVersion`
  tag: ''
  # -- The pull policy for the controller.
  pullPolicy: IfNotPresent

nameOverride: ''
fullnameOverride: ''

controller:
  # -- Create a workload for this chart.
  enabled: true
  # -- Type of the workload object.
  kind: Deployment
  # -- The number of replicas.
  replicas: 1
  strategy:
    # -- Strategy used to replace old pods.
    type: RollingUpdate
    rollingUpdate:
      # -- Specifies the maximum number of Pods that can be created over the desired number of Pods.
      maxSurge: 1
      # -- Specifies the maximum number of Pods that can be unavailable during the update process.
      maxUnavailable: 0
  # -- Additional annotations for the controller object.
  annotations: {}
  # -- Additional labels for the controller object.
  labels:
    private_network: "true"

service:
  dns:
    # -- Create a service for DNS endpoints.
    enabled: true
    # -- Combine TCP and UDP endpoints in a single service.
    single: true
    # -- The service type used.
    type: ClusterIP
    # -- The service port used.
    port: 5053
    # -- If the service is NodePort, specify a node port value here.
    nodePort: null
    # -- Additional annotations for the service object.
    annotations: {}
    # -- Additional labels for the service object.
    labels: {}

env:
  # -- Timezone for the container.
  - name: TZ
    value: UTC

serviceAccount:
  # -- Specify the service account used for the controller.
  name: ''

# -- Compute resources used by the container. More info [here](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/).
resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

# -- Pod-level affinity. More info [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling).
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: kubernetes.io/hostname
  #             operator: In
  #             values:
  #               - my-node-xyz

# -- Pod-level tolerations. More info [here](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#scheduling).
tolerations: []
  # - key: node-role.kubernetes.io/control-plane
  #   operator: Exists
  #   effect: NoSchedule
