apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.dev-sk.entrypoints: websecure
    traefik.http.routers.dev-sk.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
    traefik.http.routers.dev-sk.rule: Host(`dev.`) && !PathPrefix(`/api`) && !PathPrefix(`/_`)
    traefik.http.routers.dev-sk.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: dev-sk
  name: dev-sk
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-sk
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.enable: "true"
        traefik.http.routers.dev-sk.entrypoints: websecure
        traefik.http.routers.dev-sk.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
        traefik.http.routers.dev-sk.rule: Host(`dev.`) && !PathPrefix(`/api`) && !PathPrefix(`/_`)
        traefik.http.routers.dev-sk.tls.certresolver: leresolver
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: dev-sk
    spec:
      containers:
        - args:
            - sh
            - -c
            - npx pnpm install && npm run dev -- --host 0.0.0.0
          env:
            - name: HOME
              value: /sk
          image: node:current-alpine
          name: dev-sk
          ports:
            - containerPort: 5173
          resources: {}
          volumeMounts:
            - mountPath: /sk
              name: dev-pb-claim0
              subPath: sk/sk
            - mountPath: /pb
              name: dev-pb-claim0
              subPath: pb
          workingDir: /sk
      restartPolicy: Always
      volumes:
        - name: dev-pb-claim0
          persistentVolumeClaim:
            claimName: dev-pb-claim0
status: {}
