apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.dev-pb.entrypoints: websecure
    traefik.http.routers.dev-pb.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
    traefik.http.routers.dev-pb.rule: Host(`dev.`) && (PathPrefix(`/_`) || PathPrefix(`/api`))
    traefik.http.routers.dev-pb.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: dev-pb
  name: dev-pb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dev-pb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.enable: "true"
        traefik.http.routers.dev-pb.entrypoints: websecure
        traefik.http.routers.dev-pb.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
        traefik.http.routers.dev-pb.rule: Host(`dev.`) && (PathPrefix(`/_`) || PathPrefix(`/api`))
        traefik.http.routers.dev-pb.tls.certresolver: leresolver
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: dev-pb
    spec:
      containers:
        - args:
            - modd
          command:
            - /pb/entrypoint.sh
          workingDir: /pb
          env:
            - name: AUDITLOG
              value: posts,users
            - name: HOME
              value: /pb
          image: golang:alpine
          name: dev-pb
          ports:
            - containerPort: 8090
          resources: {}
          volumeMounts:
            - mountPath: /pb
              name: dev-pb-claim0
              subPath: pb
            - mountPath: /sk
              name: dev-pb-claim0
              subPath: sk
            - mountPath: /go/pkg
              name: dev-pb-claim0
              subPath: go/pkg
      restartPolicy: Always
      volumes:
        - name: dev-pb-claim0
          persistentVolumeClaim:
            claimName: dev-pb-claim0
status: {}
