apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.network/net: "true"
    io.kompose.service: ollama
  name: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ollama
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: ollama
    spec:
      containers:
        - image: ollama/ollama:latest
          name: ollama
          ports:
            - containerPort: 11434
          resources:
            limits:
              cpu: 10m
              memory: 200Mi
          tty: true
          volumeMounts:
            - mountPath: /code
              name: ollama-claim0
            - mountPath: /root/.ollama
              name: ollama-claim1
      restartPolicy: Always
      volumes:
        - name: ollama-claim0
          persistentVolumeClaim:
            claimName: ollama-claim0
        - name: ollama-claim1
          persistentVolumeClaim:
            claimName: ollama-claim1
status: {}
