apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: pihole
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.network/private_network: "true"
        io.kompose.service: pihole
    spec:
      containers:
        - env:
            # - name: DNS1
            #   value: 10.2.0.200
            # - name: DNS2
            #   value: 10.2.0.200
            # - name: ServerIP
            #   value: 10.1.0.100
            - name: WEBPASSWORD
              value: ""
          image: pihole/pihole:latest
          name: pihole
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /etc/pihole/
              name: pihole-claim0
            - mountPath: /etc/dnsmasq.d/
              name: pihole-claim1
      hostname: pihole
      restartPolicy: Always
      volumes:
        - name: pihole-claim0
          persistentVolumeClaim:
            claimName: pihole-claim0
        - name: pihole-claim1
          persistentVolumeClaim:
            claimName: pihole-claim1
status: {}
