apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.prod-sk.entrypoints: websecure
    traefik.http.routers.prod-sk.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
    traefik.http.routers.prod-sk.rule: Host(``) && !PathPrefix(`/api`) && !PathPrefix(`/_`)
    traefik.http.routers.prod-sk.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: prod-sk
  name: prod-sk
spec:
  ports:
    - name: "4173"
      port: 4173
      targetPort: 4173
  selector:
    io.kompose.service: prod-sk
status:
  loadBalancer: {}
