apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.prod-pb.entrypoints: websecure
    traefik.http.routers.prod-pb.middlewares: security-headers@file, error-pages-middleware@docker, ratelimit@file, geoblock@file
    traefik.http.routers.prod-pb.rule: Host(``) && (PathPrefix(`/_`) || PathPrefix(`/api`))
    traefik.http.routers.prod-pb.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: prod-pb
  name: prod-pb
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    io.kompose.service: prod-pb
status:
  loadBalancer: {}
