apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.bt.entrypoints: websecure
    traefik.http.routers.bt.middlewares: ratelimit@file, security-headers@file, error-pages-middleware, geoblock@file, auth@file
    traefik.http.routers.bt.rule: Host(`qbit.`)
    traefik.http.routers.bt.tls.certresolver: leresolver
    traefik.http.services.bt.loadbalancer.passhostheader: "false"
    traefik.http.services.bt.loadbalancer.server.port: "8093"
  creationTimestamp: null
  labels:
    io.kompose.service: qbittorrent
  name: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        traefik.enable: "true"
        traefik.http.routers.bt.entrypoints: websecure
        traefik.http.routers.bt.middlewares: ratelimit@file, security-headers@file, error-pages-middleware, geoblock@file, auth@file
        traefik.http.routers.bt.rule: Host(`qbit.`)
        traefik.http.routers.bt.tls.certresolver: leresolver
        traefik.http.services.bt.loadbalancer.passhostheader: "false"
        traefik.http.services.bt.loadbalancer.server.port: "8093"
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: qbittorrent
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: UMASK_SET
              value: "022"
            - name: WEBUI_PORT
              value: "8093"
          image: linuxserver/qbittorrent
          name: qbittorrent
          ports:
            - containerPort: 8093
            - containerPort: 6881
            - containerPort: 6881
              protocol: UDP
            - containerPort: 10625
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: qbittorrent-claim0
            - mountPath: /torrents
              name: qbittorrent-claim1
            - mountPath: /certs
              name: qbittorrent-claim2
            - mountPath: /logs
              name: qbittorrent-claim3
            - mountPath: /downloads/Completed
              name: qbittorrent-claim4
            - mountPath: /downloads/Temp
              name: qbittorrent-claim5
      restartPolicy: Always
      volumes:
        - name: qbittorrent-claim0
          persistentVolumeClaim:
            claimName: qbittorrent-claim0
        - name: qbittorrent-claim1
          persistentVolumeClaim:
            claimName: qbittorrent-claim1
        - name: qbittorrent-claim2
          persistentVolumeClaim:
            claimName: qbittorrent-claim2
        - name: qbittorrent-claim3
          persistentVolumeClaim:
            claimName: qbittorrent-claim3
        - name: qbittorrent-claim4
          persistentVolumeClaim:
            claimName: qbittorrent-claim4
        - name: qbittorrent-claim5
          persistentVolumeClaim:
            claimName: qbittorrent-claim5
status: {}
