apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.rapidbay.entrypoints: websecure
    traefik.http.routers.rapidbay.middlewares: ratelimit@file, security-headers@file, error-pages-middleware, geoblock@file
    traefik.http.routers.rapidbay.rule: Host(`rapidbay.`)
    traefik.http.routers.rapidbay.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: rapidbay
  name: rapidbay
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: rapidbay
status:
  loadBalancer: {}
