apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
    traefik.enable: "true"
    traefik.http.routers.syncthing.entrypoints: websecure
    traefik.http.routers.syncthing.middlewares: ratelimit@file, security-headers@file, error-pages-middleware, geoblock@file
    traefik.http.routers.syncthing.rule: Host(`syncthing.`)
    traefik.http.routers.syncthing.tls.certresolver: leresolver
  creationTimestamp: null
  labels:
    io.kompose.service: syncthing
  name: syncthing
spec:
  ports:
    - name: "8384"
      port: 8384
      targetPort: 8384
    - name: "22000"
      port: 22000
      targetPort: 22000
    - name: 22000-udp
      port: 22000
      protocol: UDP
      targetPort: 22000
    - name: "21027"
      port: 21027
      protocol: UDP
      targetPort: 21027
  selector:
    io.kompose.service: syncthing
status:
  loadBalancer: {}
