apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: umami-db
  name: umami-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: umami-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/umami: "true"
        io.kompose.service: umami-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: umami
            - name: POSTGRES_PASSWORD
              value: umami
            - name: POSTGRES_USER
              value: umami
          image: postgres:12-alpine
          name: umami-db
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 60
            timeoutSeconds: 10
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/schema.postgresql.sql
              name: umami-db-claim0
              readOnly: true
            - mountPath: /var/lib/postgresql/data
              name: umami-db-claim1
      restartPolicy: Always
      volumes:
        - name: umami-db-claim0
          persistentVolumeClaim:
            claimName: umami-db-claim0
            readOnly: true
        - name: umami-db-claim1
          persistentVolumeClaim:
            claimName: umami-db-claim1
status: {}
