apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: vaultwarden
  name: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vaultwarden
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/net: "true"
        io.kompose.service: vaultwarden
    spec:
      containers:
        - env:
            # - name: ADMIN_TOKEN
            #   value: 
            # - name: DOMAIN
            #   value: https://
            # - name: SIGNUPS_ALLOWED
            #   value: 
            - name: WEBSOCKET_ENABLED
              value: "true"
          image: vaultwarden/server:latest
          name: vaultwarden
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: vaultwarden-claim0
      restartPolicy: Always
      volumes:
        - name: vaultwarden-claim0
          persistentVolumeClaim:
            claimName: vaultwarden-claim0
status: {}
