apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: private-network
spec:
  podSelector:
    matchLabels:
      private_network: "true"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              private_network: "true"
