apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: browserless-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
  - repoURL: https://charts.truecharts.org
    chart: browserless-chrome
    targetRevision: 9.8.9
    helm:
      releaseName: browserless-chrome
      parameters:
      - name: "fullnameOverride"
        value: browserless-chrome
