apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: error-pages-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://geek-cookbook.github.io/charts/
      chart: error-pages
      targetRevision: 1.2.2
      helm:
        releaseName: error-pages
        parameters:
        - name: "fullnameOverride"
          value: error-pages

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values