apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: etherpad-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://nicholaswilde.github.io/helm-charts/
      chart: etherpad
      targetRevision: 1.0.2
      helm:
        releaseName: etherpad
        parameters:
        - name: "fullnameOverride"
          value: etherpad
        valueFiles:
        - $values/chart-values/etherpad-values.yaml

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values