apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flame-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://charts.truecharts.org
      chart: flame
      targetRevision: 5.8.9
      helm:
        valueFiles:
        - $values/chart-values/flame-values.yaml

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values