apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://dl.gitea.io/charts
      chart: gitea
      targetRevision: 10.1.4
      helm:
        valueFiles:
        - $values/chart-values/gitea-values.yaml

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values