apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibga-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/304442/infra
      path: charts/ibga
      targetRevision: HEAD
      helm:
        releaseName: ibga
        parameters:
        - name: "fullnameOverride"
          value: ibga

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values