apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: llama-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://otwld.github.io/ollama-helm
      chart: ollama
      targetRevision: 0.23.0
      helm:
        valueFiles:
        - $values/chart-values/ollama-values.yaml

    - repoURL: https://github.com/304442/infra
      path: charts/llama-webui
      targetRevision: HEAD

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values