apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-red-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
  - repoURL: https://charts.truecharts.org
    chart: node-red
    targetRevision: 18.8.10
    helm:
      releaseName: node-red
      parameters:
      - name: "fullnameOverride"
        value: node-red
      valueFiles:
      - $values/chart-values/nodered-values.yaml

  - repoURL: https://github.com/304442/infra
    targetRevision: HEAD
    ref: values