apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pinnwand-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/304442/infra
      path: charts/pinnwand
      targetRevision: HEAD
      helm:
        releaseName: pinnwand
        parameters:
        - name: "fullnameOverride"
          value: pinnwand
        valueFiles:
        - $values/chart-values/neko-values.yaml

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values