apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wirehole-app
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: "*"
    kind: "Deployment"
    jsonPointers:
    - /spec/template/spec/hostUsers
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  sources:
    - repoURL: https://github.com/304442/infra
      path: charts/unbound
      targetRevision: HEAD
      helm:
        releaseName: unbound
        parameters:
        - name: "fullnameOverride"
          value: unbound

    - repoURL: https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      targetRevision: 2.23.0
      helm:
        releaseName: pihole
        parameters:
        - name: "fullnameOverride"
          value: pihole
        valueFiles:
        - $values/chart-values/pihole-values.yaml

    - repoURL: https://bryopsida.github.io/wireguard-chart
      chart: wireguard
      targetRevision: 0.23.0
      helm:
        releaseName: wireguard
        parameters:
        - name: "fullnameOverride"
          value: wireguard
        valueFiles:
        - $values/chart-values/wireguard-values.yaml

    - repoURL: https://github.com/304442/infra
      path: charts/wireguard-ui
      targetRevision: HEAD
      helm:
        releaseName: wireguard-ui
        parameters:
        - name: "fullnameOverride"
          value: wireguard-ui

    - repoURL: https://github.com/304442/infra
      targetRevision: HEAD
      ref: values