annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Bump tag to 1.8.14
  artifacthub.io/images: |
    - name: etherpad
      image: ghcr.io/nicholaswilde/etherpad:version-1.8.14
apiVersion: v2
appVersion: 1.8.14
dependencies:
- name: common
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.13
- condition: mariadb.enabled
  name: mariadb
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~1.0.5
- condition: postgres.enabled
  name: postgres
  repository: https://nicholaswilde.github.io/helm-charts/
  version: ~0.1.0
description: A real-time collaborative editor scalable to thousands of simultaneous
  real time users.
home: https://github.com/nicholaswilde/helm-charts/tree/main/charts/etherpad
icon: https://github.com/nicholaswilde/helm-charts/raw/main/images/etherpad.jpg
keywords:
- etherpad
- editor
- notepad
- pad
maintainers:
- email: ncwilde43@gmail.com
  name: nicholaswilde
name: etherpad
sources:
- https://etherpad.org/
- https://github.com/ether/etherpad-lite
- https://hub.docker.com/r/nicholaswilde/etherpad
type: application
version: 1.0.2
