apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  happy-compute-ingress
  namespace: default
  annotations:
   cert-manager.io/cluster-issuer: "letsencrypt-prod"
   traefik.ingress.kubernetes.io/router.middlewares: |
     default-error-pages@kubernetescrd,
     default-secure-header@kubernetescrd,
     default-rate-limit@kubernetescrd,
     default-geoblock@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
   - hosts:
       - grafana.{{ .Values.domainName }}
       - prometheus.{{ .Values.domainName }}
       - wireguard.{{ .Values.domainName }}
       - liveide.{{ .Values.domainName }}
       - prodsk.{{ .Values.domainName }}
       - prodpb.{{ .Values.domainName }}
       - devsk.{{ .Values.domainName }}
       - devpb.{{ .Values.domainName }}
       - syncthing.{{ .Values.domainName }}
       - umami.{{ .Values.domainName }}
       - rapidbay.{{ .Values.domainName }}
       - jackett.{{ .Values.domainName }}
       - qbit.{{ .Values.domainName }}
       - browser.{{ .Values.domainName }}
       - penpot.{{ .Values.domainName }}
       - nodered.{{ .Values.domainName }}  
       - pinnwand.{{ .Values.domainName }}
       - vaultwarden.{{ .Values.domainName }}
       - neko.{{ .Values.domainName }}
       - ibga.{{ .Values.domainName }}
       - glances.{{ .Values.domainName }}
       - photoprism.{{ .Values.domainName }}
       - activepc.{{ .Values.domainName }}
       - flame.{{ .Values.domainName }}
       - llama.{{ .Values.domainName }}
       - gitea.{{ .Values.domainName }}
       - codeserver.{{ .Values.domainName }}
       - etherpad.{{ .Values.domainName }} 
     secretName: happy-tls-secret
  rules:
  - host: grafana.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: grafana
            port:
              number: 80

  - host: prometheus.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prometheus-server
            port:
              number: 80

  - host: wireguard.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wireguard-ui
            port:
              number: 5000

  - host: liveide.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: live-ide
            port:
              number: 8443

  - host: prodsk.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: happy-computing-prod-sk
            port:
              number: 4173

  - host: prodpb.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: happy-computing-prod-pb
            port:
              number: 8090

  - host: devsk.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: happy-computing-dev-sk
            port:
              number: 5173

  - host: devpb.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: happy-computing-dev-pb
            port:
              number: 8090

  - host: syncthing.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: syncthing
            port:
              number: 8384

  - host: umami.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: umami
            port:
              number: 3000

  - host: rapidbay.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: rapidbay
            port:
              number: 5000

  - host: jackett.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: jackett
            port:
              number: 9117

  - host: qbit.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: qbittorrent-webui
            port:
              number: 8080

  - host: browser.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: browserless-chrome
            port:
              number: 10194
 
  - host: penpot.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: penpot-frontend
            port:
              number: 9001

  - host: nodered.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: node-red
            port:
              number: 1880

  - host: pinnwand.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pinnwand
            port:
              number: 8000

  - host: vaultwarden.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: vaultwarden
            port:
              number: 8080

  - host: photoprism.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: photoprism
            port:
              number: 2342

  - host: glances.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: glances
            port:
              number: 61208

  - host: ibga.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ibga
            port:
              number: 5800

  - host: activepc.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: activepieces
            port:
              number: 80

  - host: flame.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: flame-app
            port:
              number: 10291

  - host: llama.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: llama-app-llama-webui
            port:
              number: 8080

  - host: gitea.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: gitea-app-http
            port:
              number: 3000

  - host: codeserver.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: code-server
            port:
              number: 8443

  - host: etherpad.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: etherpad
            port:
              number: 9001

  - host: neko.{{ .Values.domainName }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: neko
            port:
              number: 10294
